### ISSUE TITLE
[Bug] r.connectivity.distance error

### ISSUE THREAD

**Issue by ecodiv** [OSGeo/grass-addons#1088]
**Name of the addon**
r.connectivity

**Describe the bug**
When running the example from the manual page, I get the following error:

```
r.connectivity.distance -t -p input=patches_1ha pop_proxy=area_ha \
costs=costs prefix=hws_connectivity cutoff=4500 border_dist=18 \
conefor_dir=./conefor

WARNING: Cannot find GDAL-GRASS plugin. Consider installing it in order to
         save time for all-touched rasterisation
WARNING: 1 feature without category was skipped. Features without category
         are written only when -c flag is given.
WARNING: Values in column <cat> will be overwritten
Traceback (most recent call last):
  File "/home/paulo/.grass8/addons/scripts/r.connectivity.distance", line 1048, in <module>
    sys.exit(main())
  File "/home/paulo/.grass8/addons/scripts/r.connectivity.distance", line 793, in main
    to_centroid = Centroid(v_id=to_patch_ids, c_mapinfo=vpatches.c_mapinfo)
  File "/usr/local/grassmaster/grass84/etc/python/grass/pygrass/vector/geometry.py", line 1449, in __init__
    super().__init__(**kargs)
  File "/usr/local/grassmaster/grass84/etc/python/grass/pygrass/vector/geometry.py", line 458, in __init__
    super().__init__(**kargs)
  File "/usr/local/grassmaster/grass84/etc/python/grass/pygrass/vector/geometry.py", line 346, in __init__
    self.read()
  File "/usr/local/grassmaster/grass84/etc/python/grass/pygrass/errors.py", line 25, in wrapper
    return method(self, *args, **kargs)
  File "/usr/local/grassmaster/grass84/etc/python/grass/pygrass/vector/geometry.py", line 382, in read
    self.id, ftype, c_points, c_cats = c_read_line(
  File "/usr/local/grassmaster/grass84/etc/python/grass/pygrass/vector/geometry.py", line 1923, in c_read_line
    ftype = libvect.Vect_read_line(c_mapinfo, c_points, c_cats, feature_id)
ctypes.ArgumentError: argument 4: TypeError: wrong type
```

**To Reproduce**

Follow the example from the manual page of r.connectivity.distance

**Expected behavior**
The function runs without error

**Screenshots**

**System description (please complete the following information):**

- Operating System: Linux, Ubuntu 22.04
```
version=8.4.0dev
date=2024
revision=bbc3d9bb23
build_date=2024-05-19
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=23c0db50ff
libgis_date=2024-04-16T19:27:24+00:00
proj=9.3.1
gdal=3.8.4
geos=3.12.1
sqlite=3.37.2
```

**Additional context**
in line 270 of the source code, add ogr to the sub-libraries to be imported (see  #1087)

```
from osgeo import gdal, osr, ogr
```

**Comment by ninsbl** [comment]
Fixed in #1087
