### ISSUE TITLE
[Bug] r.fuzzy.system - core dump and incorrect examples

### ISSUE THREAD

**Issue by mankoff** [OSGeo/grass-addons#171]
**Name of the addon**
r.fuzzy.system

**Describe the bug**
Core dump when running a the example code. I have to run a modified version of the example code because in order for it to even start to run. Modifications included below.

**To Reproduce**

1. Run the https://grass.osgeo.org/grass78/manuals/addons/r.fuzzy.system.html example code:

```bash
grass -c ./spearfish60_grass7/fuzzy
r.stream.extract elevation=elevation.10m threshold=2000 stream_rast=streams direction=dirs
r.stream.order stream_rast=streams dir=dirs horton=horton
r.mapcalc "horton3 = if(horton>2,horton,null())"
r.stream.distance stream=streams dir=dirs elevation=elevation.10m method=downstream distance=distance
```

Changes between the code above and the example code include:

```diff
2c2
< r.stream.order stream=streams dir=dirs horton=horton
---
> r.stream.order stream_rast=streams dir=dirs horton=horton
4c4
< r.stream.distance stream=streams dir=dirs dem=elevation.10m method=downstream distance=distance elevation=elevation 
---
> r.stream.distance stream=streams dir=dirs elevation=elevation.10m method=downstream distance=distance
```

Then, when trying to run the next and most important line from the example, `r.fuzzy.system`, the following issues arise.

1. `ERROR: Raster map <elevation> not found` solved with `g.copy elevation.10m@PERMANENT,elevation`
2. `r.fuzzy.system` reports `ERROR: Raster map <flood> not found` which is strange, because `flood` is an **output map**. I can fix this by `r.mapcalc "flood = 0"` and then adding a `--overwrite` flag to the `r.fuzzy.system` call

```
r.fuzzy.system maps=flood.map rules=flood.rul output=flood --o
```

Now the code can begin to run, but

```
> r.fuzzy.system maps=flood.map rules=flood.rul output=flood --o
Calculate...
Segmentation fault (core dumped)
```

**Expected behavior**

I expect to recreate the example in the documentation

**Debug Information**

I have tried to debug this following the advice at https://grasswiki.osgeo.org/wiki/GRASS_Debugging

```bash
gdb --args ~/local/src/grass/dist.x86_64-pc-linux-gnu/bin/r.fuzzy.system maps=flood.map rules=flood.rul output=flood --o
```
and the results are:

```gdb
(gdb) run
Starting program: /home/kdm/local/src/grass/dist.x86_64-pc-linux-gnu/bin/r.fuzzy.system maps=flood.map rules=flood.rul output=flood --o
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffec351700 (LWP 2861558)]
[New Thread 0x7fffe6350700 (LWP 2861559)]
[New Thread 0x7fffe034f700 (LWP 2861560)]
[New Thread 0x7fffdc34e700 (LWP 2861561)]
[New Thread 0x7fffd834d700 (LWP 2861562)]
[New Thread 0x7fffd234c700 (LWP 2861563)]
[New Thread 0x7fffca34b700 (LWP 2861564)]
Calculate...
   0%
Thread 1 "r.fuzzy.system" received signal SIGSEGV, Segmentation fault.
0x00005555555583ac in fuzzy (cell=100000000, set=0x0) at fuzzylogic.c:8
8           if (!set->side) {           /* both left and right */
(gdb) bt full
#0  0x00005555555583ac in fuzzy (cell=100000000, set=0x0) at fuzzylogic.c:8
        x = <optimized out>
#1  0x000055555555b1fb in implicate () at system.c:37
        i = 0
        j = 0
        set_index = <optimized out>
        consequent = <optimized out>
        max_antecedent = 1
        max_agregate = 0
        result = 100000000
#2  0x0000555555557dff in main (argc=<optimized out>, argv=<optimized out>) at main.c:225
        file_vars = <optimized out>
        file_rules = <optimized out>
        par_family = <optimized out>
        par_resolution = <optimized out>
        par_defuzzify = <optimized out>
        par_implication = <optimized out>
        in_coor_opt = <optimized out>
        opt_output = <optimized out>
        history = {fields = {0x555555560210 "", 
            0x440 <error: Cannot access memory at address 0x440>, 
            0x10 <error: Cannot access memory at address 0x10>, 
            0x4000000042 <error: Cannot access memory at address 0x4000000042>, 
            0x2 <error: Cannot access memory at address 0x2>, 0x0, 0x0, 
            0x770000007c <error: Cannot access memory at address 0x770000007c>}, 
          nlines = 110, lines = 0x43414c5042444341}
        module = <optimized out>
        out_multiple = <optimized out>
        out_membership = <optimized out>
        nrows = 477
        ncols = 634
        row = 0
        col = 106
        outfd = 3
        tmp = <optimized out>
        out_buf = 0x5555555e1e10
        i = <optimized out>
        j = <optimized out>
        n = <optimized out>
(gdb) 
```

From this, and `set=0x0` I think that the set is undefined, but I am not yet sure how to fix this.

**System description (please complete the following information):**

Linux, Kubuntu 20.04. GRASS 7.8.2

```bash
g.version -rge
version=7.8.2
date=2019
revision=exported
build_date=2020-03-24
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=00000
libgis_date="?"
proj=6.3.1
gdal=3.0.4
geos=3.8.0
sqlite=3.31.1
```

**Comment by neteler** [comment]
For reasonable debugging, you would need to recompile with the debugging flag `-g` and without optimization. It should be described here: https://grasswiki.osgeo.org/wiki/GRASS_Debugging#Using_GDB (server is down right now so I cannot check)

**Comment by mankoff** [comment]
I have compiled with the suggested flags. It's been ~2 decades since I've run `gdb` on C code, so I'm a bit out of my depth.
