### ISSUE TITLE
[Bug] i.sentinel.download: incomplete except/try for sentinelsat library presence

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#201]
**Name of the addon**
i.sentinel.download crashes unelegantly on machines lacking the sentinelsat library:

```
GRASS 7.8.4dev (latlong_wgs84):~ > i.sentinel.download -l settings=~/.sentinel_esa producttype=S2MSI2A start=2018-01-01 end=2018-12-31
ERROR: Module requires sentinelsat library: No module named 'sentinelsat'
Traceback (most recent call last):
  File "/home/mneteler/.grass7/addons/scripts/i.sentinel.download", line 212, in __init__
    from sentinelsat import SentinelAPI
ModuleNotFoundError: No module named 'sentinelsat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mneteler/.grass7/addons/scripts/i.sentinel.download", line 455, in main
    downloader = SentinelDownloader(user, password, api_url)
  File "/home/mneteler/.grass7/addons/scripts/i.sentinel.download", line 214, in __init__
    gs.fatal(_("Module requires sentinelsat library: {}").format(e))
  File "/home/mneteler/software/grass78_git/dist.x86_64-pc-linux-gnu/etc/python/grass/script/core.py", line 703, in fatal
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mneteler/.grass7/addons/scripts/i.sentinel.download", line 492, in <module>
    sys.exit(main())
  File "/home/mneteler/.grass7/addons/scripts/i.sentinel.download", line 476, in main
    except StandardError as e:
NameError: name 'StandardError' is not defined
```

**Describe the bug**
The error message should appear properly and the undefined variable be fixed.

**Software**
- GRASS GIS 7.8 dev
- `python --version`: Python 3.8.3

**Comment by neteler** [comment]
Aha: The `StandardError` class was removed in Python 3:

https://portingguide.readthedocs.io/en/latest/exceptions.html#the-removed-standarderror

**Comment by neteler** [comment]
BTW: The only (to be corrected?) instance in GRASS-core I see here

https://github.com/OSGeo/grass/blob/5fa5d69f568ccf2d8551bc4f7858dd7f26f2cfaa/temporal/t.register/t.register.py#L143

**Comment by veroandreo** [comment]
> BTW: The only (to be corrected?) instance in GRASS-core I see here
> 
> https://github.com/OSGeo/grass/blob/5fa5d69f568ccf2d8551bc4f7858dd7f26f2cfaa/temporal/t.register/t.register.py#L143

Maybe this is worth a bug report in grass repo...

**Comment by neteler** [comment]
TODO: Adopt solution suggested by @landam in https://github.com/OSGeo/grass/issues/701#issuecomment-644377026
