### ISSUE TITLE
[Bug] v.in.pygbif crashes with ERROR 1: missing [

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#235]
**Name of the addon**
v.in.pygbif

**Describe the bug**

It crashes..:

```
GRASS 7.8.4dev (latlong_wgs84):~gbif > v.in.pygbif taxa="Plantae" rank=kingdom -p
ERROR 1: missing [
Traceback (most recent call last):
  File "/home/mundialis/.grass7/addons/scripts/v.in.pygbif", line 815, in <module>
    sys.exit(main())
  File "/home/mundialis/.grass7/addons/scripts/v.in.pygbif", line 460, in main
    target.ImportFromProj4(target_crs)
  File "/usr/lib64/python3.6/site-packages/osgeo/osr.py", line 1223, in ImportFromProj4
    return _osr.SpatialReference_ImportFromProj4(self, *args)
TypeError: in method 'SpatialReference_ImportFromProj4', argument 1 of type 'OSRSpatialReferenceShadow *'
Segmentation fault (core dumped)
```

(note: the https://grass.osgeo.org/grass7/manuals/addons/v.in.pygbif.html#examples crashes as well)

**System description:**
 - Centos 8
 - pygbif-0.4.0-py2.py3-none-any.whl (installed with pip3)

```
g.version -rge
version=7.8.4dev
date=2020
revision=a0a0c9361
build_date=2020-06-13
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=8e4dab571
libgis_date=2020-05-05T09:05:27+00:00
proj=6.3.2
gdal=3.0.4
geos=3.7.2
sqlite=3.26.0

Python 3.6.8
```

**Comment by ninsbl** [comment]
Hm. Thanks for the heads up.
I have a fix for the issue (likely related to GDAL 3 changes).

However, v.in.pygbif does not seem to find any species (though the pounding box looks OK)...
Have to investigate a bit more...
