### ISSUE TITLE
[Bug] r.in.wcs: TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by ecodiv** [OSGeo/grass-addons#327]
**Name of the addon**
r.in.wcs.

**Describe the bug**
Running the addon gives me the following error
```
r.in.wcs url=https://maps.isric.org/mapserv? coverage=wrb output=wrb
Importing raster map into GRASS...
Traceback (most recent call last):
  File "/home/paulo/.grass7/addons/scripts/r.in.wcs", line 485, in <module>
    sys.exit(main())
  File "/home/paulo/.grass7/addons/scripts/r.in.wcs", line 476, in main
    fetched_map = wcs.GetMap(options,flags)
  File "/home/paulo/.grass7/addons/scripts/r.in.wcs", line 233, in GetMap
    p = self._download()
  File "/home/paulo/.grass7/addons/scripts/r.in.wcs", line 400, in _download
    self.vrt_file = self._createVRT()
  File "/home/paulo/.grass7/addons/scripts/r.in.wcs", line 384, in _createVRT
    grass.verbose(self.err+"\n")
TypeError: can't concat str to bytes
```
**To Reproduce**
Run e.g., 
``` 
r.in.wcs url=https://maps.isric.org/mapserv? coverage=wrb output=wrb
```

**Expected behavior**
Download the wcs layer

**System description (please complete the following information):**
 - Operating System: Linux, Ubuntu 20.04
 - GRASS GIS version: 7.8.4 (installed via UbuntuGIS unstable)

**Comment by tmszi** [comment]
Could @ecodiv test again, please?

**Comment by ecodiv** [comment]
Hi @tmszi thanks, that solved the issue. There is now another issue, for which I will create a new ticket
