### ISSUE TITLE
[Bug]  i.landsat.qa: use dataset option from i.landsat.download

### ISSUE THREAD

**Issue by ninsbl** [OSGeo/grass-addons#456]
**i.landsat.qa**

**Describe the bug**
i.landsat.qa should also use the dataset option from i.landsat.download for consistency and seamless user experience.

**To Reproduce**
See options in the mentioned modules

**Additional context**
See discussion in #455

**Comment by neteler** [comment]
While at it: I don't seem to get `i.landsat.qa` running for collection 2:

```
GRASS nc_spm_08_grass7/user1 >

# download 1 scene
i.landsat.download settings=~/.usgs dataset=landsat_etm_c2_l2 clouds=30 start='2004-01-15' end='2004-01-15' output=~/tmp/usgs_lsat7/
1 scenes found.
Downloading scene <LE70150352004015EDC01> ...
257MB [00:13, 20.0MB/s]              

# import
GRASS nc_spm_08_grass7/user1:grass_master > i.landsat.import input=~/tmp/usgs_lsat7/ pattern='B(1|2|3|4|5|7)' -r register_output=~/tmp/usgs_lsat7/lsat7_tgrass.csv 

g.region raster=LE07_L1TP_015035_20040115_20160927_01_T1_B1 -p

# QA
i.landsat.qa collection=2 sensor="Landsat_7_ETM+" cloud="Medium,High" output=~/tmp/usgs_lsat7/Cloud_Mask_rules.txt
Traceback (most recent call last):
  File "/home/mneteler/.grass7/addons/scripts/i.landsat.qa", line 379, in <module>
    sys.exit(main())
  File "/home/mneteler/.grass7/addons/scripts/i.landsat.qa", line 353, in main
    bits = single_bits[bp]
KeyError: 'Medium'

i.landsat.qa collection=2 sensor="Landsat_7_ETM+" cloud=no cloud_confidence="Medium,High" output=~/tmp/usgs_lsat7/Cloud_Mask_rules.txt
Traceback (most recent call last):
  File "/home/mneteler/.grass7/addons/scripts/i.landsat.qa", line 379, in <module>
    sys.exit(main())
  File "/home/mneteler/.grass7/addons/scripts/i.landsat.qa", line 353, in main
    bits = single_bits[bp]
KeyError: 'no'
```

**Comment by neteler** [comment]
@ninsbl, do you have any hint?

**Comment by ninsbl** [comment]
Yes, started actually working on it. I hope I can fix that in the course of the weekend...

**Comment by ninsbl** [comment]
The solution is most likely to add a check for the input.

> # QA
> i.landsat.qa collection=2 sensor="Landsat_7_ETM+" cloud="Medium,High" output=~/tmp/usgs_lsat7/Cloud_Mask_rules.txt
> Traceback (most recent call last):
>   File "/home/mneteler/.grass7/addons/scripts/i.landsat.qa", line 379, in <module>
>     sys.exit(main())
>   File "/home/mneteler/.grass7/addons/scripts/i.landsat.qa", line 353, in main
>     bits = single_bits[bp]
> KeyError: 'Medium'

The `cloud` option refers to a single bit, so only `No` or `Yes`are allowed.
Can you try:
`i.landsat.qa collection=2 sensor="Landsat_7_ETM+" cloud="Yes" output=~/tmp/usgs_lsat7/Cloud_Mask_rules.txt`

> i.landsat.qa collection=2 sensor="Landsat_7_ETM+" cloud=no cloud_confidence="Medium,High" output=~/tmp/usgs_lsat7/Cloud_Mask_rules.txt
> Traceback (most recent call last):
>   File "/home/mneteler/.grass7/addons/scripts/i.landsat.qa", line 379, in <module>
>     sys.exit(main())
>   File "/home/mneteler/.grass7/addons/scripts/i.landsat.qa", line 353, in main
>     bits = single_bits[bp]
> KeyError: 'no'
> ```

The options are case sensitive, so it should be "No" or "Yes", maybe I should make it all lower case...
Can you try:
` i.landsat.qa collection=2 sensor="Landsat_7_ETM+" cloud=Yes cloud_confidence="Medium,High" output=~/tmp/usgs_lsat7/Cloud_Mask_rules.txt`

**Comment by neteler** [comment]
> The solution is most likely to add a check for the input.
> Can you try:
> `i.landsat.qa collection=2 sensor="Landsat_7_ETM+" cloud="Yes" output=~/tmp/usgs_lsat7/Cloud_Mask_rules.txt`

This works.
 
> Can you try:
> ` i.landsat.qa collection=2 sensor="Landsat_7_ETM+" cloud=Yes cloud_confidence="Medium,High" output=~/tmp/usgs_lsat7/Cloud_Mask_rules.txt`

Also works.

The two resulting files (expectedly) differ to some extent.

**Comment by neteler** [comment]
With your input I was able to continue and generate the cloud mask, thanks.

Just curious: when having multiple Landsat scenes in the download folder, I suppose I'd want to generate multiple cloud mask maps?

**Comment by veroandreo** [comment]
> With your input I was able to continue and generate the cloud mask, thanks.
> 
> Just curious: when having multiple Landsat scenes in the download folder, I suppose I'd want to generate multiple cloud mask maps?

Yes, indeed, as they are specific for the conditions of each scene.
