### ISSUE TITLE
[Bug] r.learn.ml2: test_append failure

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#495]
At time this test fails:

```
Test      | test_append
Testsuite | ./raster/r.learn.ml2
Test file | ./raster/r.learn.ml2/testsuite/test_append.py
Status    | FAILED

Standard error output (stderr)

..x.ERROR: lsat7_2002_10@landsat: Cannot remove or exclude files not in the current mapset.
E
======================================================================
ERROR: tearDownClass (__main__.TestAppend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "raster/r.learn.ml2/testsuite/test_append.py", line 46, in tearDownClass
    gs.run_command("g.remove", type="raster", name=cls.other, flags="f")
  File "etc/python/grass/script/core.py", line 543, in run_command
    return handle_errors(returncode, result=None, args=args, kwargs=kwargs)
  File "etc/python/grass/script/core.py", line 428, in handle_errors
    raise CalledModuleError(module=module, code=code, returncode=returncode)
grass.exceptions.CalledModuleError: Module run g.remove g.remove -f type=raster name=lsat7_2002_10@landsat ended with error
Process ended with non-zero return code 1. See errors in the (error) output.

----------------------------------------------------------------------
Ran 4 tests in 0.174s

FAILED (errors=1, expected failures=1)
```

The problem might be that here the `@landsat` part is given:

https://github.com/OSGeo/grass-addons/blob/a5ec8b618f2cb6cc65c4f9aad194b6c5aa2fe8ac/grass7/raster/r.learn.ml2/testsuite/test_append.py#L40

Since the test runs in another mapset, this original map cannot be removed (and should not) in `tearDownClass()`.
Might be easy to fix...

Log source: [GitHub actions](https://pipelines.actions.githubusercontent.com/bj0E8CyHydhmaJ5zP4W1C63cIPHft1BErACunoYnYSbroXtwhp/_apis/pipelines/1/runs/1259/signedartifactscontent?artifactName=testreport-grass-master-python-3.6&urlExpires=2021-03-28T20%3A27%3A38.6900065Z&urlSigningMethod=HMACV1&urlSignature=ETyJcNwlgcWRm1Kkftn%2BNDwc5BYUJV0Xuk6R1%2FoQoUw%3D)

**Comment by stevenpawley** [comment]
Fixed with #645
