### ISSUE TITLE
[Bug] r.bioclim fails 

### ISSUE THREAD

**Issue by ecodiv** [OSGeo/grass-addons#703]
**Name of the addon**
r.bioclim

**Describe the bug**
r.bioclim stops with the error message below:

```
C:\Users\brp>r.bioclim precipitation=prec_196101,prec_196102,prec_196103,prec_196104,prec_196105,prec_196106,prec_196107,prec_196108,prec_196109,prec_196110,prec_196111,prec_196112 tmin=tmin_196101,tmin_196102,tmin_196103,tmin_196104,tmin_196105,tmin_196106,tmin_196107,tmin_196108,tmin_196109,tmin_196110,tmin_196111,tmin_196112 tmax=tmax_196101,tmax_196102,tmax_196103,tmax_196104,tmax_196105,tmax_196106,tmax_196107,tmax_196108,tmax_196109,tmax_196110,tmax_196111,tmax_196112 output=bioclim quartals=12 --overwrite
Calculating monthly averages from min and max
 100%
 100%
 100%
 100%
 100%
 100%
 100%
 100%
 100%
 100%
 100%
 100%
BIO1 = Annual Mean Temperature ...
> notaracter <al filename <bioclim.tavg12.13168
         allowed.
> not founder map <bioclim.tavg12.13168
Traceback (most recent call last):
  File "C:\Users\brp\AppData\Roaming\GRASS8\addons\scripts\r.bioclim.py", line 796, in <module>
    main()
  File "C:\Users\brp\AppData\Roaming\GRASS8\addons\scripts\r.bioclim.py", line 176, in main
    grass.run_command("r.series", input=tavg, output=output, method="average")
  File "C:\Program Files\GRASS GIS 8.1\etc\python\grass\script\core.py", line 541, in run_command
    return handle_errors(returncode, result=None, args=args, kwargs=kwargs)
  File "C:\Program Files\GRASS GIS 8.1\etc\python\grass\script\core.py", line 429, in handle_errors
    raise CalledModuleError(module=module, code=code, returncode=returncode)
grass.exceptions.CalledModuleError: Module run `r.series input=bioclim.tavg01.13168,bioclim.tavg02.13168,bioclim.tavg03.13168,bioclim.tavg04.13168,bioclim.tavg05.13168,bioclim.tavg06.13168,bioclim.tavg07.13168,bioclim.tavg08.13168,biocli output=bioclimbio01.13168 method=average` ended with an error.m.tavg12.13168
The subprocess ended with a non-zero return code: 1. See errors above the traceback or in the error output.
```

**To Reproduce**
1. run r.bioclim with the required input

**Expected behavior**
Run and calculate the bio1 - bio12 variables. Now it stops after computing bio1

**Screenshots**

**System description (please complete the following information):**
 - Operating System: Windows 10
 - GRASS GIS version [e.g. 8.1dev]

**Additional context**

**Comment by ecodiv** [comment]
Tested on Ubuntu 20.04, GRASS GIS version 7.8.6 and 8.0. In both cases, the addon works as advertised, so the problem is with Windows.

**Comment by neteler** [comment]
Looking at the error message
`grass.exceptions.CalledModuleError: Module run 'r.series input=bioclim.tavg01.13168...`
the input map line looks cut (see error above).

Just guessing: Perhaps the module needs to be changed to use `r.series file=inputmaps.csv ...`  ?
