### ISSUE TITLE
[Bug] r.roughness.vector extension install issue

### ISSUE THREAD

**Issue by Chris35Wills** [OSGeo/grass-addons#717]
r.roughness.vector

**Describe the bug**

Unable to install r.roughness.vector extension with grass78 using g.extension with url set to

"https://github.com/OSGeo/grass-addons/tree/grass8/src/raster/r.roughness.vector"
or
"http://svn.osgeo.org/grass/grass-addons/grass7/raster/r.roughness.vector"
or
"http://svn.osgeo.org/grass/grass-addons/grass7"

Note that the extension is already installed on my system from a time when this worked, and for the purpose here, I'm allowing a reinstall as part of a program to make sure up-to-date.

**To Reproduce**

Steps to reproduce the behavior - I've tried different URLs (and the default with no user URL provided):

```
grass_extension_path="https://github.com/OSGeo/grass-addons/tree/grass8/src/raster/r.roughness.vector"
#grass_extension_path="http://svn.osgeo.org/grass/grass-addons/grass7/raster/r.roughness.vector"
#grass_extension_path="http://svn.osgeo.org/grass/grass-addons/grass7"
gs.run_command('g.extension', extension="r.roughness.vector", url=grass_extension_path)
#gs.run_command('g.extension', extension="r.roughness.vector")
```

**Expected behavior**

Expect install to happen without error messages.

**Screenshots/Terminal output of different attempts**

```python
>>> grass_extension_path="https://github.com/OSGeo/grass-addons/tree/grass8/src/raster/r.roughness.vector"
>>> gs.run_command('g.extension', extension="r.roughness.vector", url=grass_extension_path)
WARNING: Extension <r.roughness.vector> already installed. Re-installing...
Fetching <r.roughness.vector> from
<https://github.com/OSGeo/grass-addons/tree/grass8/src/raster/r.roughness.vector/archive/master.zip>
(be patient)...
ERROR: Extension <r.roughness.vector> not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cm/shared/apps/grass/7.8.3/grass78/etc/python/grass/script/core.py", line 441, in run_command
    return handle_errors(returncode, returncode, args, kwargs)
  File "/cm/shared/apps/grass/7.8.3/grass78/etc/python/grass/script/core.py", line 343, in handle_errors
    returncode=returncode)
  File "/cm/shared/apps/grass/7.8.3/grass78/etc/python/grass/exceptions/__init__.py", line 68, in __init__
    msg = _("Module run %s %s ended with error") % (module, code)
TypeError: 'int' object is not callable
```

```python
>>> grass_extension_path="http://svn.osgeo.org/grass/grass-addons/grass7/raster/r.roughness.vector"
>>> gs.run_command('g.extension', extension="r.roughness.vector", url=grass_extension_path)
WARNING: Extension <r.roughness.vector> already installed. Re-installing...
Fetching <r.roughness.vector> from
<http://svn.osgeo.org/grass/grass-addons/grass7/raster/r.roughness.vector>
(be patient)...
Error validating server certificate for 'https://svn.osgeo.org:443':
 - The certificate has expired.
 - The certificate has an unknown error.
Certificate information:
 - Hostname: svn.osgeo.org
 - Valid: from Tue, 25 Jan 2022 05:29:40 GMT until Mon, 25 Apr 2022 05:29:39 GMT
 - Issuer: Let's Encrypt, US
 - Fingerprint: 84:4b:2a:0a:51:ef:29:8a:a1:9a:70:ad:32:e6:95:72:dc:9a:3e:1a
(R)eject or accept (t)emporarily? r
svn: E175002: Unable to connect to a repository at URL 'https://svn.osgeo.org/grass/grass-addons/grass7/raster/r.roughness.vector/raster/r.roughness.vector'
svn: E175002: OPTIONS of 'https://svn.osgeo.org/grass/grass-addons/grass7/raster/r.roughness.vector/raster/r.roughness.vector': Server certificate verification failed: certificate has expired, bad certificate chain (https://svn.osgeo.org)
ERROR: GRASS Addons <r.roughness.vector> not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cm/shared/apps/grass/7.8.3/grass78/etc/python/grass/script/core.py", line 441, in run_command
    return handle_errors(returncode, returncode, args, kwargs)
  File "/cm/shared/apps/grass/7.8.3/grass78/etc/python/grass/script/core.py", line 343, in handle_errors
    returncode=returncode)
  File "/cm/shared/apps/grass/7.8.3/grass78/etc/python/grass/exceptions/__init__.py", line 68, in __init__
    msg = _("Module run %s %s ended with error") % (module, code)
TypeError: 'int' object is not callable
```

```python
>>>grass_extension_path="http://svn.osgeo.org/grass/grass-addons/grass7/raster/r.roughness.vector"
>>> gs.run_command('g.extension', extension="r.roughness.vector", url=grass_extension_path)
WARNING: Extension <r.roughness.vector> already installed. Re-installing...
Fetching <r.roughness.vector> from
<http://svn.osgeo.org/grass/grass-addons/grass7/raster/r.roughness.vector>
(be patient)...
Error validating server certificate for 'https://svn.osgeo.org:443':
 - The certificate has expired.
 - The certificate has an unknown error.
Certificate information:
 - Hostname: svn.osgeo.org
 - Valid: from Tue, 25 Jan 2022 05:29:40 GMT until Mon, 25 Apr 2022 05:29:39 GMT
 - Issuer: Let's Encrypt, US
 - Fingerprint: 84:4b:2a:0a:51:ef:29:8a:a1:9a:70:ad:32:e6:95:72:dc:9a:3e:1a
(R)eject or accept (t)emporarily? t
svn: E170000: URL 'https://svn.osgeo.org/grass/grass-addons/grass7/raster/r.roughness.vector/raster/r.roughness.vector' doesn't exist
ERROR: GRASS Addons <r.roughness.vector> not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cm/shared/apps/grass/7.8.3/grass78/etc/python/grass/script/core.py", line 441, in run_command
    return handle_errors(returncode, returncode, args, kwargs)
  File "/cm/shared/apps/grass/7.8.3/grass78/etc/python/grass/script/core.py", line 343, in handle_errors
    returncode=returncode)
  File "/cm/shared/apps/grass/7.8.3/grass78/etc/python/grass/exceptions/__init__.py", line 68, in __init__
    msg = _("Module run %s %s ended with error") % (module, code)
TypeError: 'int' object is not callable
```

```python
>>> grass_extension_path="http://svn.osgeo.org/grass/grass-addons/grass7"
>>> gs.run_command('g.extension', extension="r.roughness.vector", url=grass_extension_path)
WARNING: Extension <r.roughness.vector> already installed. Re-installing...
Fetching <r.roughness.vector> from
<http://svn.osgeo.org/grass/grass-addons/grass7> (be patient)...
Error validating server certificate for 'https://svn.osgeo.org:443':
 - The certificate has expired.
 - The certificate has an unknown error.
Certificate information:
 - Hostname: svn.osgeo.org
 - Valid: from Tue, 25 Jan 2022 05:29:40 GMT until Mon, 25 Apr 2022 05:29:39 GMT
 - Issuer: Let's Encrypt, US
 - Fingerprint: 84:4b:2a:0a:51:ef:29:8a:a1:9a:70:ad:32:e6:95:72:dc:9a:3e:1a
(R)eject or accept (t)emporarily? t
Compiling...
Traceback (most recent call last):
  File "/cm/shared/apps/grass/7.8.3/grass78/tools/mkhtml.py", line 266, in <module>
    src_data = read_file(src_file)
  File "/cm/shared/apps/grass/7.8.3/grass78/tools/mkhtml.py", line 158, in read_file
    return decode(s)
  File "/cm/shared/apps/grass/7.8.3/grass78/tools/mkhtml.py", line 66, in decode
    return bytes_.decode(enc)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 2523: invalid continuation byte
make: *** [/tmp/tmp6z1hiaug/r.roughness.vector/docs/html/r.roughness.vector.html] Error 1
ERROR: Compilation failed, sorry. Please check above error messages.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cm/shared/apps/grass/7.8.3/grass78/etc/python/grass/script/core.py", line 441, in run_command
    return handle_errors(returncode, returncode, args, kwargs)
  File "/cm/shared/apps/grass/7.8.3/grass78/etc/python/grass/script/core.py", line 343, in handle_errors
    returncode=returncode)
  File "/cm/shared/apps/grass/7.8.3/grass78/etc/python/grass/exceptions/__init__.py", line 68, in __init__
    msg = _("Module run %s %s ended with error") % (module, code)
TypeError: 'int' object is not callable
```

```python
>>> gs.run_command('g.extension', extension="r.roughness.vector")
WARNING: Extension <r.roughness.vector> already installed. Re-installing...
Fetching <r.roughness.vector> from GRASS GIS Addons repository (be
patient)...
svn: E170000: URL 'https://github.com/OSGeo/grass-addons/trunk/grass7/raster/r.roughness.vector' doesn't exist
ERROR: GRASS Addons <r.roughness.vector> not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cm/shared/apps/grass/7.8.3/grass78/etc/python/grass/script/core.py", line 441, in run_command
    return handle_errors(returncode, returncode, args, kwargs)
  File "/cm/shared/apps/grass/7.8.3/grass78/etc/python/grass/script/core.py", line 343, in handle_errors
    returncode=returncode)
  File "/cm/shared/apps/grass/7.8.3/grass78/etc/python/grass/exceptions/__init__.py", line 68, in __init__
    msg = _("Module run %s %s ended with error") % (module, code)
TypeError: 'int' object is not callable
```

**System description**
 - Operating System: UNIX
 - GRASS GIS version: 7.8.3
- details about further software components:
    - version=7.8.3
    - date=2020
    - revision=exported
    - build_date=2020-07-22
    - build_platform=x86_64-pc-linux-gnu
    - build_off_t_size=8
    - libgis_revision=2020-07-22T22:16:21+00:00
    - libgis_date=2020-07-21T17:00:00+01:00
    - proj=7.0.0
    - gdal=3.0.4
    - geos=3.8.1
    - sqlite=3.32.3
    - 0

**Additional context**
This is for a HPC application and as you'll see, I'm invoking everything via the Python API.

**Comment by petrasovaa** [comment]
GRASS 7.8.3 is too old for this, there has been a lot of changes in restructuring the addons repository. So please either update your GRASS, or download the repository locally and then install using g.extension, see:
https://grass.osgeo.org/grass78/manuals/g.extension.html#installing-when-writing-a-module-locally
